name: deploy tafaria-castle
run-name: ${{ github.actor }} is deploying ${{ github.repository }}
on: 
    push:
        branches: [ main ]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy using ssh
              uses: appleboy/ssh-action@master
              with:
                host: 209.38.189.197
                username: chris
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                    if [ ! command -v pm2 &> /dev/null ];
                    then
                        npm install -g pm2
                    fi

                    if [ ! -d /var/www/tafaria-castle ]; then
                        sudo mkdir -p /var/www/tafaria-castle
                        sudo chown -R root:chris /var/www/tafaria-castle
                        sudo chmod -R 770 /var/www/tafaria-castle
                    fi
                    if [ ! -d ~/tafaria-castle ]; then
                        git clone https://github.com/goodlifechris/tafaria-castle.git
                        if [ $? -ne 0 ]; then
                            echo "Failed to clone the repository"
                            exit 1
                        fi
                    fi
                    cd ~/tafaria-castle
                    git fetch
                    git pull

                    npm install
                    npm run build
                    if [ $? -ne 0 ]; then
                        echo "Failed to build the project"
                        exit 1
                    fi
                    cp -ru ~/tafaria-castle/{package.json,next.config.js,public,.next,node_modules} /var/www/tafaria-castle
                    
                    if [ ! -d /var/www/tafaria-castle ]; then
                        echo "Failed to create the directory"
                        exit 1
                    fi
                    cd /var/www/tafaria-castle

                    if pm2 ls | grep -qw 'tafaria-castle'; then
                        pm2 reload tafaria-castle --time
                    else
                        pm2 start npm --name "tafaria-castle" -- start --time
                        pm2 save
                    fi
